/**
 * Homepage banner carousel.
 *
 * The WebP files are generated by scripts/build-banners.mjs from the artwork in
 * ../首页轮播图片. Only the dimensional facts come from the generated manifest.
 *
 * Alt text lives here, not in the manifest, on purpose: it is editorial copy and
 * keeping it out of generated output means re-running the converter can never
 * overwrite it. (image-manifest.json takes the opposite approach, which is why
 * regenerating the product images discards hand-written alt.)
 *
 * These strings join the text blob scripts/verify-content.mjs scans, so nothing
 * here may carry a price, an area, a headcount or a capacity figure.
 */
import manifest from './banner-manifest.json';

export type Banner = {
  /** Public path of the generated WebP. */
  src: string;
  /** Describes what the photograph shows; the slides carry no visible caption. */
  alt: string;
};

type BannerSlug = keyof typeof manifest;

/**
 * Slide order is fixed here rather than derived from the manifest, so
 * regenerating the artwork cannot silently reshuffle the carousel.
 */
export const BANNER_ORDER = [
  'airtight-zipper',
  'dry-suit-zipper',
  'inflatable-boat-zipper',
  'tpu-airtight-zipper',
  'waterproof-zipper',
] as const satisfies readonly BannerSlug[];

const ALT: Record<(typeof BANNER_ORDER)[number], string> = {
  'airtight-zipper':
    'An airtight zipper shown underwater at sunset, with the IPX8 rating badge alongside it',
  'dry-suit-zipper':
    'A scuba diver in a dry suit, with a close-up of the drysuit zipper in a circular inset',
  'inflatable-boat-zipper':
    'An inflatable boat on a lake, with a close-up of the boat zipper in a circular inset',
  'tpu-airtight-zipper':
    'A backpack on wet grass in the rain, with a close-up of its TPU airtight zipper in a circular inset',
  'waterproof-zipper': 'Close-up of a waterproof zipper covered in water droplets',
};

export const banners: Banner[] = BANNER_ORDER.map((slug) => ({
  src: manifest[slug].src,
  alt: ALT[slug],
}));
